### ISSUE TITLE
some crash issue, help?

### ISSUE THREAD

**Issue by DragonDaSilva** [Thuts-Mods/ThutTech#15]
--versions--

thutcore - 1.16.3 - 8.0.0
thuttech - 1.16.3 - 9.0.0

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 18/01/21 16:25
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6838/395736241.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6417/278853255.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$452/1115296438.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
-- MOD thuttech --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at thut.tech.common.TechCore$RegistryEvents.registerRecipes(TechCore.java:68) ~[?:9.0.0] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_179_RegistryEvents_registerRecipes_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3229/1684428673.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2922/2016200186.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2923/768856989.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$452/1115296438.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

	Mod File: thuttech-1.16.3-9.0.0.jar
	Failure message: Thut Elevators (thuttech) encountered an error during the load_registries event phase
		java.lang.ExceptionInInitializerError: null
	Mod Version: 9.0.0
	Mod Issue URL: https://github.com/Thutmose/Thut/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.item.crafting.IRecipeSerializer.func_222156_a(IRecipeSerializer.java:39) ~[?:?] {re:classloading}
	at thut.tech.common.items.RecipeReset.<clinit>(RecipeReset.java:14) ~[?:9.0.0] {re:classloading}
	at thut.tech.common.TechCore$RegistryEvents.registerRecipes(TechCore.java:68) ~[?:9.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_179_RegistryEvents_registerRecipes_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3229/1684428673.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2922/2016200186.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2923/768856989.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$452/1115296438.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 955244832 bytes (910 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.42.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.42-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |COMMON_SET|NOSIGNATURE
		repurposed_structures-1.16.3-2.2.11.jar           |Repurposed Structures         |repurposed_structures         |1.16.3-2.2.11       |COMMON_SET|NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |COMMON_SET|NOSIGNATURE
		AmbientSounds_v3.1.1_mc1.16.3.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |COMMON_SET|NOSIGNATURE
		BiomesOPlenty-1.16.3-12.0.0.417-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.3-12.0.0.416   |COMMON_SET|NOSIGNATURE
		Wyrmroost-1.16.3-1.2.7.jar                        |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.7        |COMMON_SET|NOSIGNATURE
		Let-Sleeping-Dogs-Lie-Mod-1.16.3.jar              |Let Sleeping Dogs Lie         |dogslie                       |1.1.1               |COMMON_SET|NOSIGNATURE
		dungeons-plus-1.16.3-1.0.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.0.3               |COMMON_SET|NOSIGNATURE
		CreativeCore_v2.0.8_mc1.16.4.jar                  |CreativeCore                  |creativecore                  |2.0.0               |COMMON_SET|NOSIGNATURE
		treeharvester_1.16.3-2.0.jar                      |Tree Harvester                |treeharvester                 |2.0                 |COMMON_SET|NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |COMMON_SET|NOSIGNATURE
		movingelevators-1.2.31a-mc1.16.3.jar              |Moving Elevators              |movingelevators               |1.2.31a             |COMMON_SET|NOSIGNATURE
		NetherEnhanced-1.16.3-0.3.jar                     |Nether Enhanced               |netherenhanced                |0.1                 |COMMON_SET|NOSIGNATURE
		fishingreal-1.16.3-1.0.0.jar                      |Fishing Real                  |fishingreal                   |1.0.0               |COMMON_SET|NOSIGNATURE
		Fairy-Lights-Mod-1.16.3.jar                       |Fairy Lights                  |fairylights                   |4.0.0               |COMMON_SET|NOSIGNATURE
		Doggy-Talents-Mod-1.16.3.jar                      |Doggy Talents 2               |doggytalents                  |2.0.1.0             |COMMON_SET|NOSIGNATURE
		justmobheads_1.16.3-3.7.jar                       |Just Mob Heads                |justmobheads                  |3.7                 |COMMON_SET|NOSIGNATURE
		simplybackpacks-1.16.3-1.4.13.jar                 |Simply Backpacks              |simplybackpacks               |1.16.3-1.4.13       |COMMON_SET|NOSIGNATURE
		Craftable+Saddles+[1.16.3]-1.3.jar                |Craftable Saddles             |craftable_saddles             |1.3                 |COMMON_SET|NOSIGNATURE
		curios-forge-1.16.3-4.0.2.0 (1).jar               |Curios API                    |curios                        |1.16.3-4.0.2.0      |COMMON_SET|NOSIGNATURE
		CoffeeSpawner-1.16.3-7.0.0.jar                    |Coffee Spawner                |coffeespawner                 |1.16.3-7.0.0        |COMMON_SET|NOSIGNATURE
		Xaeros_Minimap_20.29.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.29.1             |COMMON_SET|NOSIGNATURE
		collective-1.16.3-1.53.jar                        |Collective                    |collective                    |1.53                |COMMON_SET|NOSIGNATURE
		citadel-1.4.1.jar                                 |Citadel                       |citadel                       |1.4.1               |COMMON_SET|NOSIGNATURE
		NaturesCompass-1.16.3-1.8.5 (1).jar               |Nature's Compass              |naturescompass                |1.16.3-1.8.5        |COMMON_SET|NOSIGNATURE
		Artifacts-1.16.3-2.6.0.jar                        |Artifacts                     |artifacts                     |1.16.3-2.6.0        |COMMON_SET|NOSIGNATURE
		angelring-1.16.3-1.3.3.jar                        |Angel Ring                    |angelring                     |1.3.3               |COMMON_SET|NOSIGNATURE
		backpacked-1.7.0-mc1.16.3.jar                     |Backpacked                    |backpacked                    |1.7.0               |COMMON_SET|NOSIGNATURE
		backpacker-1.1.0-mc1.16.3.jar                     |Backpacker                    |backpacker                    |1.1.0               |COMMON_SET|NOSIGNATURE
		good-nights-sleep-1.16.3-1.2.8.jar                |Good Night's Sleep            |good_nights_sleep             |1.2.8               |COMMON_SET|NOSIGNATURE
		structurize-0.13.92-ALPHA-universal.jar           |Structurize                   |structurize                   |0.13.92-ALPHA       |COMMON_SET|NOSIGNATURE
		minecolonies-0.13.406-BETA-universal.jar          |Minecolonies                  |minecolonies                  |0.13.406-BETA       |COMMON_SET|NOSIGNATURE
		TelePastries-Mod-1.16.3.jar                       |TelePastries                  |telepastries                  |0.3.4.1             |COMMON_SET|NOSIGNATURE
		cfm-7.0.0-pre19-mc1.16.3.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |COMMON_SET|NOSIGNATURE
		mcw-furniture-2.0.0-mc1.16.3.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.0               |COMMON_SET|NOSIGNATURE
		iceandfire-2.1.1-1.16.3.jar                       |Ice and Fire                  |iceandfire                    |2.0.3-1.16.3        |COMMON_SET|NOSIGNATURE
		the_bumblezone-1.16.4-2.2.8.jar                   |The Bumblezone                |the_bumblezone                |1.16.4-2.2.8        |COMMON_SET|NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Aquaculture-1.16.3-2.1.4.jar                      |Aquaculture 2                 |aquaculture                   |1.16.3-2.1.4        |COMMON_SET|NOSIGNATURE
		[1.16.X-1.0.10]+Dragon+Mounts+Legacy.jar          |Dragon Mounts: Legacy         |dragonmounts                  |1.0.10              |COMMON_SET|NOSIGNATURE
		blame-1.7.4.jar                                   |Blame!                        |blame                         |1.7.4               |COMMON_SET|NOSIGNATURE
		thutcore-1.16.3-8.0.0.jar                         |Thut Core                     |thutcore                      |8.0.0               |COMMON_SET|NOSIGNATURE
		thuttech-1.16.3-9.0.0.jar                         |Thut Elevators                |thuttech                      |9.0.0               |VALIDATE  |NOSIGNATURE
		structure-gel-api-1.16.3-1.6.0.jar                |Structure Gel API             |structure_gel                 |1.6.0               |COMMON_SET|NOSIGNATURE
	Crash Report UUID: 49c51dc9-4c41-4750-a10a-1bc48dd92aea
	OptiFine Version: OptiFine_1.16.3_HD_U_G5
	OptiFine Build: 20201106-202857
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7926
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by Thutmose** [comment]
try updating forge for 1.16.4, and then also update the mods, see if the issue still occurs?
